# Generated by Django 3.0.8 on 2020-08-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
